# Generated by Django 3.2.8 on 2021-10-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211006_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='myMessages',
            field=models.ManyToManyField(blank=True, to='api.Message'),
        ),
    ]
