# Generated by Django 3.2.8 on 2021-10-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_utilisateur_mymessages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='mail',
            new_name='email',
        ),
    ]
